services:
  app:
    build: .
    image: hajupe/hnh-servers:1
    container_name: hnh-app
    ports:
      - "8080:8080"
    depends_on:
      - nginx
    environment:
      - AWS_IAM_ACCESS_KEY=${AWS_IAM_ACCESS_KEY}
      - AWS_IAM_SECRET_KEY=${AWS_IAM_SECRET_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - JPA_HIBERNATE_DDL=${JPA_HIBERNATE_DDL}
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_URL=jdbc:mysql://hnh-server.c14ko6688c0b.ap-northeast-2.rds.amazonaws.com/hnh?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - JWT_SECRET=036c4fe3ec667532545b9e8fa7e2a98a22f439dff102623c097715060e2da68c
      - REDIS_HOST=hnh-redis-001.qgyfa2.0001.apn2.cache.amazonaws.com
      - REDIS_PORT=6379

    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf